{
 "title": "Chia Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Farmer target address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_reward_address_info", "legendFormat": "{{ farmer_target }}" }
   ]
  },
  {
   "title": "Pool target address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_reward_address_info", "legendFormat": "{{ pool_target }}" }
   ]
  },
  {
   "title": "sync state",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_sync_state{chia_sync_state=\"synced\"}"
    }
   ]
  },
  {
   "title": "Total XCH Farmed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_farmed_amount/1000000000000"
    }
   ]
  },
  {
   "title": "Last farmed block",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_farmed_last_block" }
   ]
  },
  {
   "title": "Est. netspace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "chia_netspace_total" }
   ]
  },
  {
   "title": "Current height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_block_height" }
   ]
  },
  {
   "title": "Plot count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_plots_count" }
   ]
  },
  {
   "title": "Plot size",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_plots_size" }
   ]
  },
  {
   "title": "Time to win",
   "type": "graph",
   "description": "As the \"farm summary\" calculates it",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "chia_time_to_win" }
   ]
  },
  {
   "title": "Seconds per block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "chia_average_block_time" }
   ]
  }
 ]
}